services:
  jobmaster.sqlserver:
    env_file:
      - .env
    ports:
      - "1439:1433"
    volumes:
      - jobmaster.sqlserver:/var/opt/mssql
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
  jobmaster.api:
    env_file:
      - .env
    ports:
      - "${API_HTTP_PORT}:8080"
      - "${API_HTTPS_PORT}:8081"
    depends_on:
      jobmaster.sqlserver:
        condition: service_healthy
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  jobmaster.web:
    env_file:
      - .env
    ports:
      - "${APP_PORT}:4200"
    depends_on:
      - jobmaster.api